---
- name: Install Abiquo packages for an RS server
  yum: name={{ item }} state=present
  with_items:
    - abiquo-remote-services
    - abiquo-sosreport-plugins
    - jdk

- name: Ensure abiquo/config folder exists
  file: path=/opt/abiquo/config state=directory

- name: Import SSL certificate from API endpoint into Java keystore
  java_cert:
    cert_url: "{{ ui_server_name }}"
    keystore_path: /usr/java/default/jre/lib/security/cacerts
    keystore_pass: changeit
  notify: restart abiquo-tomcat
  register: certimported

- name: Force tomcat restart for cert import
  meta: flush_handlers
  when: certimported.changed
