---
- name: Install Abiquo packages for an V2V server
  yum:
    name:
      - jdk
      - abiquo-v2v
      - abiquo-sosreport-plugins
    state: present

- name: Ensure abiquo/config folder exists
  file: path=/opt/abiquo/config state=directory

- name: Start services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - abiquo-tomcat
    - rpcbind
