---
- name: Install Abiquo packages for an V2V server
  yum: name={{ item }} state=present
  with_items:
    - jdk
    - abiquo-v2v
    - abiquo-sosreport-plugins

- name: Ensure abiquo/config folder exists
  file: path=/opt/abiquo/config state=directory
